name: coin_gecko
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  get: 4.6.5
  modal_progress_hud_nsn: ^0.3.0
  flutter_spinkit: ^5.1.0
  flutter_flavor: ^3.1.1
  shared_preferences: ^2.0.18
  dio: ^5.0.3
  cached_network_image: ^3.2.3
  money2: ^3.3.0
  intl: ^0.17.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

